/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResponderLinkPublicoRouteImport } from './routes/responder.$linkPublico'
import { Route as AuthPerfilRouteImport } from './routes/_auth/perfil'
import { Route as AuthNr1RouteImport } from './routes/_auth/nr1'
import { Route as AuthEmpresasRouteImport } from './routes/_auth/empresas'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthConfiguracoesRouteImport } from './routes/_auth/configuracoes'
import { Route as AuthConfiguracoesIndexRouteImport } from './routes/_auth/configuracoes.index'
import { Route as AuthNr1IdRouteImport } from './routes/_auth/nr1.$id'
import { Route as AuthEmpresasIdRouteImport } from './routes/_auth/empresas.$id'
import { Route as AuthConfiguracoesIaRouteImport } from './routes/_auth/configuracoes.ia'
import { Route as AuthConfiguracoesCatalogoSubescalasRouteImport } from './routes/_auth/configuracoes.catalogo-subescalas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderLinkPublicoRoute = ResponderLinkPublicoRouteImport.update({
  id: '/responder/$linkPublico',
  path: '/responder/$linkPublico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNr1Route = AuthNr1RouteImport.update({
  id: '/nr1',
  path: '/nr1',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmpresasRoute = AuthEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConfiguracoesRoute = AuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConfiguracoesIndexRoute = AuthConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthConfiguracoesRoute,
} as any)
const AuthNr1IdRoute = AuthNr1IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthNr1Route,
} as any)
const AuthEmpresasIdRoute = AuthEmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEmpresasRoute,
} as any)
const AuthConfiguracoesIaRoute = AuthConfiguracoesIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthConfiguracoesRoute,
} as any)
const AuthConfiguracoesCatalogoSubescalasRoute =
  AuthConfiguracoesCatalogoSubescalasRouteImport.update({
    id: '/catalogo-subescalas',
    path: '/catalogo-subescalas',
    getParentRoute: () => AuthConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/empresas': typeof AuthEmpresasRouteWithChildren
  '/nr1': typeof AuthNr1RouteWithChildren
  '/perfil': typeof AuthPerfilRoute
  '/responder/$linkPublico': typeof ResponderLinkPublicoRoute
  '/configuracoes/catalogo-subescalas': typeof AuthConfiguracoesCatalogoSubescalasRoute
  '/configuracoes/ia': typeof AuthConfiguracoesIaRoute
  '/empresas/$id': typeof AuthEmpresasIdRoute
  '/nr1/$id': typeof AuthNr1IdRoute
  '/configuracoes/': typeof AuthConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/empresas': typeof AuthEmpresasRouteWithChildren
  '/nr1': typeof AuthNr1RouteWithChildren
  '/perfil': typeof AuthPerfilRoute
  '/responder/$linkPublico': typeof ResponderLinkPublicoRoute
  '/configuracoes/catalogo-subescalas': typeof AuthConfiguracoesCatalogoSubescalasRoute
  '/configuracoes/ia': typeof AuthConfiguracoesIaRoute
  '/empresas/$id': typeof AuthEmpresasIdRoute
  '/nr1/$id': typeof AuthNr1IdRoute
  '/configuracoes': typeof AuthConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/configuracoes': typeof AuthConfiguracoesRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/empresas': typeof AuthEmpresasRouteWithChildren
  '/_auth/nr1': typeof AuthNr1RouteWithChildren
  '/_auth/perfil': typeof AuthPerfilRoute
  '/responder/$linkPublico': typeof ResponderLinkPublicoRoute
  '/_auth/configuracoes/catalogo-subescalas': typeof AuthConfiguracoesCatalogoSubescalasRoute
  '/_auth/configuracoes/ia': typeof AuthConfiguracoesIaRoute
  '/_auth/empresas/$id': typeof AuthEmpresasIdRoute
  '/_auth/nr1/$id': typeof AuthNr1IdRoute
  '/_auth/configuracoes/': typeof AuthConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/nr1'
    | '/perfil'
    | '/responder/$linkPublico'
    | '/configuracoes/catalogo-subescalas'
    | '/configuracoes/ia'
    | '/empresas/$id'
    | '/nr1/$id'
    | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/empresas'
    | '/nr1'
    | '/perfil'
    | '/responder/$linkPublico'
    | '/configuracoes/catalogo-subescalas'
    | '/configuracoes/ia'
    | '/empresas/$id'
    | '/nr1/$id'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/configuracoes'
    | '/_auth/dashboard'
    | '/_auth/empresas'
    | '/_auth/nr1'
    | '/_auth/perfil'
    | '/responder/$linkPublico'
    | '/_auth/configuracoes/catalogo-subescalas'
    | '/_auth/configuracoes/ia'
    | '/_auth/empresas/$id'
    | '/_auth/nr1/$id'
    | '/_auth/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResponderLinkPublicoRoute: typeof ResponderLinkPublicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/$linkPublico': {
      id: '/responder/$linkPublico'
      path: '/responder/$linkPublico'
      fullPath: '/responder/$linkPublico'
      preLoaderRoute: typeof ResponderLinkPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/nr1': {
      id: '/_auth/nr1'
      path: '/nr1'
      fullPath: '/nr1'
      preLoaderRoute: typeof AuthNr1RouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/empresas': {
      id: '/_auth/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthEmpresasRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/configuracoes': {
      id: '/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthConfiguracoesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/configuracoes/': {
      id: '/_auth/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthConfiguracoesIndexRouteImport
      parentRoute: typeof AuthConfiguracoesRoute
    }
    '/_auth/nr1/$id': {
      id: '/_auth/nr1/$id'
      path: '/$id'
      fullPath: '/nr1/$id'
      preLoaderRoute: typeof AuthNr1IdRouteImport
      parentRoute: typeof AuthNr1Route
    }
    '/_auth/empresas/$id': {
      id: '/_auth/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof AuthEmpresasIdRouteImport
      parentRoute: typeof AuthEmpresasRoute
    }
    '/_auth/configuracoes/ia': {
      id: '/_auth/configuracoes/ia'
      path: '/ia'
      fullPath: '/configuracoes/ia'
      preLoaderRoute: typeof AuthConfiguracoesIaRouteImport
      parentRoute: typeof AuthConfiguracoesRoute
    }
    '/_auth/configuracoes/catalogo-subescalas': {
      id: '/_auth/configuracoes/catalogo-subescalas'
      path: '/catalogo-subescalas'
      fullPath: '/configuracoes/catalogo-subescalas'
      preLoaderRoute: typeof AuthConfiguracoesCatalogoSubescalasRouteImport
      parentRoute: typeof AuthConfiguracoesRoute
    }
  }
}

interface AuthConfiguracoesRouteChildren {
  AuthConfiguracoesCatalogoSubescalasRoute: typeof AuthConfiguracoesCatalogoSubescalasRoute
  AuthConfiguracoesIaRoute: typeof AuthConfiguracoesIaRoute
  AuthConfiguracoesIndexRoute: typeof AuthConfiguracoesIndexRoute
}

const AuthConfiguracoesRouteChildren: AuthConfiguracoesRouteChildren = {
  AuthConfiguracoesCatalogoSubescalasRoute:
    AuthConfiguracoesCatalogoSubescalasRoute,
  AuthConfiguracoesIaRoute: AuthConfiguracoesIaRoute,
  AuthConfiguracoesIndexRoute: AuthConfiguracoesIndexRoute,
}

const AuthConfiguracoesRouteWithChildren =
  AuthConfiguracoesRoute._addFileChildren(AuthConfiguracoesRouteChildren)

interface AuthEmpresasRouteChildren {
  AuthEmpresasIdRoute: typeof AuthEmpresasIdRoute
}

const AuthEmpresasRouteChildren: AuthEmpresasRouteChildren = {
  AuthEmpresasIdRoute: AuthEmpresasIdRoute,
}

const AuthEmpresasRouteWithChildren = AuthEmpresasRoute._addFileChildren(
  AuthEmpresasRouteChildren,
)

interface AuthNr1RouteChildren {
  AuthNr1IdRoute: typeof AuthNr1IdRoute
}

const AuthNr1RouteChildren: AuthNr1RouteChildren = {
  AuthNr1IdRoute: AuthNr1IdRoute,
}

const AuthNr1RouteWithChildren =
  AuthNr1Route._addFileChildren(AuthNr1RouteChildren)

interface AuthRouteRouteChildren {
  AuthConfiguracoesRoute: typeof AuthConfiguracoesRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEmpresasRoute: typeof AuthEmpresasRouteWithChildren
  AuthNr1Route: typeof AuthNr1RouteWithChildren
  AuthPerfilRoute: typeof AuthPerfilRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConfiguracoesRoute: AuthConfiguracoesRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEmpresasRoute: AuthEmpresasRouteWithChildren,
  AuthNr1Route: AuthNr1RouteWithChildren,
  AuthPerfilRoute: AuthPerfilRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResponderLinkPublicoRoute: ResponderLinkPublicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
